config/routes.rb
Photogur::Application.routes.draw do
  
  resources :pictures do
    resources :comments
  end

  root :to => 'pictures#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
  attr_accessible :content, :name
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :artist, :title, :url

  #validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
 
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comments.create(params[:comment])
    redirect_to picture_path(@picture)
  end

  def destroy
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comments.find(params[:id])
    @comment.destroy
    redirect_to picture_path(@picture)
  end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	


	def index
		@pictures = Picture.all
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def new
		@picture = Picture.new
	end

 def create

  @picture = Picture.new(params[:picture])
  if @picture.save
    
    redirect_to pictures_url
  else

    render :new
  end
end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])

		if @picture.update_attributes(params[:picture])
			redirect_to "/pictures/#{@picture.id}"
		else
			render :edit
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>Name:</b>
  <%= comment.name %>
</p>
 
<p>
  <b>Content:</b>
  <%= comment.content %>
</p>

<p>
  <%= link_to 'Delete', [comment.picture, comment], 
  						 :class => "btn",
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@picture, @picture.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header class="navbar navbar-fixed-top navbar-inverse">
  	<div class="navbar-inner">
    	<div class="container">
      	<%= link_to "Photogur", pictures_url, id: "logo" %>
      	<nav>
        	<ul class="nav pull-right">
          	<li><%= link_to "Home",    pictures_url %></li>
          	<li><%= link_to "Add pic",    "/pictures/new" %></li>
        	</ul>
      	</nav>
    	</div>
  	</div>
	</header>

<div class="container">
	<%= yield %>
	<footer class="footer">
  	<small>
    	<a href="https://github.com/bolonomicz/photogur">PHOTOGUR</a>
   	 by Ralph Bolo
  	</small>
  	<nav>
    	<ul>
      	<li><%= link_to "Contact", 'https://twitter.com/bolonomicz' %></li>
     	</ul>
  	</nav>
	</footer>
</div>


</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
	<%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
	<p>
		<%= f.label "artist" %><br>
		<%= f.text_field "artist" %>
	</p>
	<p>
		<%= f.label "title" %><br>
		<%= f.text_field "title" %>
	</p>
	<p>
		<%= f.label "url" %><br>
		<%= f.text_field "url" %>
	</p>
	<p>
		<%= submit_tag "Save" %>
	</p>
	<% end %>

	

app/views/pictures/index.html.erb
<h1>Pictures</h1>


<% @pictures.each do |picture| %>
	<div>

	
	<%= link_to "pictures/#{picture.id}" do %>
		<img src="<%= picture[:url] %>">
	<% end %>
  	<h6><%= picture[:title] %><br> <em>by</em> <%= picture[:artist] %></h6>


  </div>

<% end %>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pictures_url %>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/pictures/picture0.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src="<%= @picture[:url] %>">

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url, :class => "btn" %>  <%= link_to "Edit", edit_picture_path(@picture), :class => "btn" %>  <%= link_to "Delete", @picture, :class => "btn", :confirm => "Are you sure you want to delete this picture?", :method => :delete, :class => "btn" %>


<p><%= @picture[:title] %> <em>by</em> <%= @picture[:artist] %></p>
<img src="<%= @picture[:url] %>">

<div class="row">
	<div class="span6">
		<h2>Comments</h2>
		<%= render @picture.comments %>
	</div>

	<div class="span6">
		<h2>Add a comment:</h2>
		<%= render "comments/form" %>
	</div> 
</div>